#!/usr/bin/env python

import sys
import validator


BRANCHES_WITH_BUILD = ['master', 'staging', 'platformdev']

if validator.get_current_branch() in BRANCHES_WITH_BUILD:
	sys.exit(validator.lint() + validator.js_lint() + validator.build())
	print "build script running post-commit"


	
