#!/usr/bin/env python

import sys
import validator

if not validator.has_valid_branch_point(validator.get_current_branch()):
	branch_status = 1
else:
	branch_status = 0
	
if not validator.is_valid_merge():
	branch_status = 1

if branch_status == 0:
	sys.exit(validator.lint() + validator.js_lint())
else:
	sys.exit(1)

