#!/usr/bin/env python

import sys
import validator

if not validator.has_valid_branch_point(validator.get_current_branch()):
	status = 1
else:
	status = validator.lint() +  validator.js_lint()
sys.exit(status)
